name: 'Terraform'

on: [push, pull_request]

env:
  TF_LOG: INFO

  jobs:
  terraform:
    name: 'Terraform'
    runs-on: amzn2-ami-kernel-5.10-hvm-2.0.20221103.3-x86_64-gp2


    defaults:
      run:
        shell: bash
        working-directory: ./main

steps:

    - name: Checkout
      uses: actions/checkout@v2


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.6

    - name: Terraform Init
          id: init
          env:
      
      name: Terraform Format
        id: fmt

      name: Terraform Validate
        id: validates  

      name: Terraform Plan
        id: plan
      
      name: Terraform Apply      
        id: apply
